### PR TITLE
Add prose scope example

### PR DESCRIPTION
**Pull request by 36degrees**
Add an example of the prose scope being applied to some example HTML so that contributors can understand how their changes to Frontend might affect it.

https://trello.com/c/Jtron4KD/574-add-prose-scope-example

### CODE REVIEW

**Comment by joelanman** [comment]
@amyhupe and I had a discussion previously about sample content. It's a bit tricky using real guidance, as it can easily get out of date. One solution we thought of was using 'historical' content that is much less likely to change, say an announcement. Alternatively just ipsum lorem

**Comment by 36degrees** [comment]
This is exactly the same content as we currently have in one of the typography examples, so this isn't introducing anything new. Agree that we should review what content we're using generally, but I don't think we need to address it as part of this PR.

**Comment by joelanman** [comment]
ah ok, good point. However, this sample doesn't cover uls and ols, which is provided by prose-scope - do we want a sample that will cover that? The sample in the design system is here:

https://govuk-design-system-production.cloudapps.digital/styles/typography/prose-scope/index.html

**Comment by 36degrees** [comment]
Good call, will update.

**Comment by 36degrees** [comment]
@joelanman have updated with a new example based on the example in the design system, but with headings directly following each other, an example of a longer list item and a few links.

**Pull request merged**
