### PR TITLE
WIP: Update date component: remove Nunjucks attributions and use classes for errors

### PR DESCRIPTION
**Pull request by alex-ju**
This PR:
* removes unnecessary attributions in template Nunjucks file
* uses classes instead of boolean attributes to pass errors to inputs

### CODE REVIEW

**Comment by 36degrees** [comment]
We're currently inconsistent on passing in classes vs setting classes based on other logic so, given we'll likely talk about this tomorrow, do we want to hold off merging this until we've decided one way or the other?

**Comment by alex-ju** [comment]
@36degrees sure, can wait.

**Comment by alex-ju** [comment]
@36degrees shall I close this PR? or update on the same branch when its time comes (e.g. input component is ready)?

**Comment by 36degrees** [comment]
Let's close this for now.

**Pull request closed without merging**
