### PR TITLE
Remove JavaScript from Details component

### PR DESCRIPTION
**Pull request by domoscargin**
Part of #3464

### CODE REVIEW

**Review by 36degrees — APPROVED** [review]
Needs a changelog entry, but otherwise makes me very happy to see this being tidied into oblivion 🗑️

**Comment by 36degrees** [comment]
@domoscargin what needs to be done to get this out of draft / mergeable? 🙂

**Comment by domoscargin** [comment]
@36degrees I was waiting till #3758 is ready, since merging this PR will create the styling issue with older browsers which aren't polyfilled.

Otherwise we could take the view that we're going to merge #3758 shortly anyway, and get this one merged sooner? Happy either way.

**Comment by colinrotherham** [comment]
@domoscargin How about I merge the ES2015 classes first in #3771 but then rebase this branch for you, avoiding any conflicts?

**Comment by domoscargin** [comment]
@colinrotherham Was just opening this up to do a rebase, but since you're close to the work, go ahead!

**Comment by colinrotherham** [comment]
@domoscargin Rebased this one + https://github.com/alphagov/govuk-frontend/pull/3758

**Pull request merged**
