### PR TITLE
Nest components correctly

### PR DESCRIPTION
**Pull request by nickcolley**
Fixes https://github.com/alphagov/govuk-frontend/issues/531

Best viewed commit by commit.

For the README generation commit you might want to use this link with whitespace removed from the diff: https://github.com/alphagov/govuk-frontend/pull/584/commits/1efae42fb6c211cfb9c334859f843a75d0be6b33?w=1

### CODE REVIEW

**Comment by nickcolley** [comment]
@igloosi yeah I think so, I was being cheeky and hoping I could sneak it in this one.

**Comment by igloosi** [comment]
:)

**Comment by nickcolley** [comment]
Okay, okay, I'll split it out 👼

**Comment by igloosi** [comment]
thanks, just the chnagelog left

**Pull request merged**
