### PR TITLE
Add brand colour for Department for Levelling Up, Housing and Communities (DLUHC)

### PR DESCRIPTION
**Pull request by brucebolt**
This is a new department, so adding a new brand colour for this organisation.

[Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4712566)

### CODE REVIEW

**Review by owenatgov — APPROVED** [review]
LGTM

**Comment by brucebolt** [comment]
Thanks @owenatgov.  I don't have permissions to merge on this repo, would you be able to do it for me?

**Comment by owenatgov** [comment]
I don't have permissions either sadly. Have prompted the design system team who'll have a look in a bit.

**Review by vanitabarrett — APPROVED** [review]

**Comment by vanitabarrett** [comment]
Thanks for raising this @brucebolt - looks good to me. This just needs a second review from someone in the Design System team before it can be merged.

**Review by lfdebrux — APPROVED** [review]

**Pull request merged**
