### PR TITLE
[WIP] DAC accessibility examples

### PR DESCRIPTION
**Pull request by CharlotteDowns**
This is an example of what we want to have in the Frontend Review App to take to the Digital Accessibility Centre for an Audit. 

This pull request is **not intended to be merged** into `main`

We need to add examples for:

- [x] Step-by-step
- [x] Task list (Using PR #2261 )
- [x] Check a phone number from the gov.uk account team
- [x] Header with menu variant
- [x] Input with a prefix or suffix (or both)
- [x] Small checkboxes
- [x] Small radios
- [x] 'Success' notification banner

We need to improve the [full-page-examples page](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples) to include the other examples and a scenario for each if applicable.

### For reviewers

Areas that explicitly need a review:

#### General review
- [ ] Any updates to Exit this page component
- [ ] Whether examples match those in the Design System patterns including: error states
#### Content and design review
- [ ] Choice of content in examples
- [ ] Reviewing the scenario examples in the example index files
#### Code review
- [ ] Downsizing the commit history
- [ ] Proper use of ARIA, as prescribed for the individual components
- [ ] General correctness of code
- [ ] Validation and posting
- [ ] Adherence to HTML spec
- [ ] Proper use of nunjucks and correct use of the various available variables

### CODE REVIEW

**Comment by querkmachine** [comment]
Code-wise this seems hunky-dory so far! I only noticed a couple of deviations from our current code and design patterns. 

- **What is your address:** Address line 2's label is visually hidden. This isn't the case in the pattern in the Design System, however. Should it be visible? 
- **What is your address:** The town/city field is missing the `autocomplete="address-level2"` attribute from the Design System's pattern.
- **What is your national insurance number:** The page lacks an H1. I imagine this should follow the [one-thing-per-page pattern](https://design-system.service.gov.uk/components/text-input/input-hint-text/index.html) and have the form label also be an H1.
 
A few other random noticings: 

- **Child maintenance:** Various links lead to 404 pages. Not sure if we need to change these? 
- **Child maintenance:** The Exit this Page button and skiplink lead to different places. This was the case in the review app for testing purposes, but we may want to change it here.
- **Work history:** Multiple links have the label "Delete work history". [We already know this is a bit dodgy](https://github.com/alphagov/govuk-design-system/issues/2680), do we want to amend it for the audit or do we want DAC's opinion on whether it's actually an issue?
- **Work history:** Submit button leads to 404 page.

**Comment by querkmachine** [comment]
Some more suggestions for consistency:

- **Feedback**: The name and email address fields are [missing `autocomplete` attributes](https://design-system.service.gov.uk/components/text-input/#use-the-autocomplete-attribute). 
- **Make a payment**: Reduce the width of the input to be more [appropriate for the expected value](https://design-system.service.gov.uk/components/text-input/#use-appropriately-sized-text-inputs). `govuk-input--width-5` looks about right to my eye.  
- **What are your bank details** & **What is your National Insurance number**: We've now shipped the `govuk-input--extra-letter-spacing` class and updated the [bank details](https://design-system.service.gov.uk/patterns/bank-details/) and [National Insurance number](https://design-system.service.gov.uk/patterns/national-insurance-numbers/) patterns to use it. Presumably we now want to do the same here?

**Comment by owenatgov** [comment]
Closing as we're done with DAC auditing for the mo

**Comment by CharlotteDowns** [comment]
Reopening as we are gearing up for a retest

**Comment by CharlotteDowns** [comment]
### Examples that are different between this pull request and one of the latest pull requests of the review app #5046 

- [Make a payment](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/make-a-payment)
- [Search three pages](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/search-three-pages)
- [What are your bank details](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/what-are-your-bank-details)
- What is your address (was edited to follow the [Ask users for addresses](https://design-system.service.gov.uk/patterns/addresses/) pattern)
- [What is your date of birth](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/what-is-your-date-of-birth)
- [What is your national insurance number](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/what-is-your-national-insurance-number)
- [What is your phone number](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/what-is-your-phone-number)
- [Will you be travelling to any of these countries](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/will-you-be-travelling-to-any-of-these-countries)

**Comment by querkmachine** [comment]
Retests were done against a new PR: #5088. I think this one is safe to close off again now.

**Pull request closed without merging**
