### PR TITLE
Allow input type to be overridden; Update date input to use type="number"

### PR DESCRIPTION
**Pull request by 36degrees**
See individual commits for details.

https://trello.com/c/gpdeKWhm/695-make-date-input-component-use-typenumber

### CODE REVIEW

**Comment by joelanman** [comment]
I have the same concerns here as with the `max` property. With type=number, some users will enter things and nothing happens at all - there's no messaging about what's gone wrong. However in this case it does have a significant advantage of displaying a more useful keyboard to touchscreen users. Is type="number" the only way to do that?

**Comment by edwardhorsford** [comment]
From memory, `type=tel` more reliably produces a numeric keypad. I'd have to check our notes.

Nothing happens if a user types a non-numeric character, but I wonder if this is actually a problem in reality - it may help users catch issues quicker - and it's standard browser behavior.

**Comment by 36degrees** [comment]
This is just aligning Frontend with what we already have in Elements.

**Comment by nickcolley** [comment]
This needs an addition to the changelog @36degrees

**Pull request merged**
