### PR TITLE
Release v3.10.0

### PR DESCRIPTION
**Pull request by 36degrees**
### Update users with notification banners

You can now [use notification banners](https://design-system.service.gov.uk/components/notification-banner/) to tell users about events that occur elsewhere in your service. For example, when they need to complete tasks.

This was added in [pull request #1935: Create notification banner component](https://github.com/alphagov/govuk-frontend/issues/1935).

### Customise input mode in the date component

You can now change which keyboard type displays for mobile and tablet users. This enables users to enter characters other than numbers when they use the date input. To change the keyboard type, set the `inputmode` when you use the Nunjucks macro options.

This was added in [pull request #1975: Enable custom inputmode for date input component](https://github.com/alphagov/govuk-frontend/pull/1975). Thanks to @foaly-nr1  for contributing this issue.

### CODE REVIEW

**Comment by 36degrees** [comment]
## Changes to `dist`

```diff
diff --git a/dist/VERSION.txt b/dist/VERSION.txt
index 3c2201ed..80798f32 100644
--- a/dist/VERSION.txt
+++ b/dist/VERSION.txt
@@ -1 +1 @@
-3.9.1
+3.10.0
diff --git a/dist/govuk-frontend-3.9.1.min.css b/dist/govuk-frontend-3.10.0.min.css
similarity index 49%
rename from dist/govuk-frontend-3.9.1.min.css
rename to dist/govuk-frontend-3.10.0.min.css
index d54937e9..a7fbfbcb 100644
--- a/dist/govuk-frontend-3.9.1.min.css
+++ b/dist/govuk-frontend-3.10.0.min.css
@@ -3160,24 +3160,45 @@
 }
 
 .govuk-error-summary__list a {
-    font-weight: 700
+    font-weight: 700;
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale
 }
 
-.govuk-error-summary__list a:active,
-.govuk-error-summary__list a:hover,
-.govuk-error-summary__list a:link,
-.govuk-error-summary__list a:visited {
-    color: #d4351c
+@media print {
+    .govuk-error-summary__list a {
+        font-family: sans-serif
+    }
 }
 
 .govuk-error-summary__list a:focus {
     outline: 3px solid rgba(0, 0, 0, 0);
-    color: #0b0c0c;
     background-color: #fd0;
     box-shadow: 0 -2px #fd0, 0 4px #0b0c0c;
     text-decoration: none
 }
 
+.govuk-error-summary__list a:link {
+    color: #d4351c
+}
+
+.govuk-error-summary__list a:visited {
+    color: #4c2c92
+}
+
+.govuk-error-summary__list a:hover {
+    color: #942514
+}
+
+.govuk-error-summary__list a:active {
+    color: #d4351c
+}
+
+.govuk-error-summary__list a:focus {
+    color: #0b0c0c
+}
+
 .govuk-file-upload {
     font-family: GDS Transport, arial, sans-serif;
     -webkit-font-smoothing: antialiased;
@@ -3975,6 +3996,230 @@ only screen and (min-resolution:192dpi) {
     margin-bottom: 0
 }
 
+.govuk-notification-banner {
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale;
+    font-weight: 400;
+    font-size: 16px;
+    font-size: 1rem;
+    line-height: 1.25;
+    margin-bottom: 30px;
+    border: 5px solid #1d70b8
+}
+
+@media print {
+    .govuk-notification-banner {
+        font-family: sans-serif
+    }
+}
+
+@media (min-width:40.0625em) {
+    .govuk-notification-banner {
+        font-size: 19px;
+        font-size: 1.1875rem;
+        line-height: 1.31579
+    }
+}
+
+@media print {
+    .govuk-notification-banner {
+        font-size: 14pt;
+        line-height: 1.15
+    }
+}
+
+@media (min-width:40.0625em) {
+    .govuk-notification-banner {
+        margin-bottom: 50px
+    }
+}
+
+.govuk-notification-banner:focus {
+    outline: 3px solid #fd0
+}
+
+.govuk-notification-banner__header {
+    padding: 2px 15px 5px;
+    border-bottom: 1px solid rgba(0, 0, 0, 0);
+    background-color: #1d70b8
+}
+
+@media (min-width:40.0625em) {
+    .govuk-notification-banner__header {
+        padding: 2px 20px 5px
+    }
+}
+
+.govuk-notification-banner__title {
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale;
+    font-weight: 700;
+    font-size: 16px;
+    font-size: 1rem;
+    line-height: 1.25;
+    margin: 0;
+    padding: 0;
+    color: #fff
+}
+
+@media print {
+    .govuk-notification-banner__title {
+        font-family: sans-serif
+    }
+}
+
+@media (min-width:40.0625em) {
+    .govuk-notification-banner__title {
+        font-size: 19px;
+        font-size: 1.1875rem;
+        line-height: 1.31579
+    }
+}
+
+@media print {
+    .govuk-notification-banner__title {
+        font-size: 14pt;
+        line-height: 1.15
+    }
+}
+
+.govuk-notification-banner__content {
+    margin: 15px
+}
+
+@media (min-width:40.0625em) {
+    .govuk-notification-banner__content {
+        margin: 20px
+    }
+}
+
+.govuk-notification-banner__heading {
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale;
+    font-weight: 700;
+    font-size: 18px;
+    font-size: 1.125rem;
+    line-height: 1.11111;
+    margin: 0 0 15px;
+    padding: 0
+}
+
+@media print {
+    .govuk-notification-banner__heading {
+        font-family: sans-serif
+    }
+}
+
+@media (min-width:40.0625em) {
+    .govuk-notification-banner__heading {
+        font-size: 24px;
+        font-size: 1.5rem;
+        line-height: 1.25
+    }
+}
+
+@media print {
+    .govuk-notification-banner__heading {
+        font-size: 18pt;
+        line-height: 1.15
+    }
+}
+
+.govuk-notification-banner__link {
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale
+}
+
+@media print {
+    .govuk-notification-banner__link {
+        font-family: sans-serif
+    }
+}
+
+.govuk-notification-banner__link:focus {
+    outline: 3px solid rgba(0, 0, 0, 0);
+    background-color: #fd0;
+    box-shadow: 0 -2px #fd0, 0 4px #0b0c0c;
+    text-decoration: none
+}
+
+.govuk-notification-banner__link:link {
+    color: #1d70b8
+}
+
+.govuk-notification-banner__link:visited {
+    color: #4c2c92
+}
+
+.govuk-notification-banner__link:hover {
+    color: #003078
+}
+
+.govuk-notification-banner__link:active,
+.govuk-notification-banner__link:focus {
+    color: #0b0c0c
+}
+
+.govuk-notification-banner--success {
+    border-color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__header {
+    background-color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:link {
+    color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:visited {
+    color: #4c2c92
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:hover {
+    color: #004e2a
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:active {
+    color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:focus {
+    color: #0b0c0c
+}
+
+.govuk-notification-banner--error {
+    border-color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__header {
+    background-color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:link {
+    color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:visited {
+    color: #4c2c92
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:hover {
+    color: #942514
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:active {
+    color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:focus {
+    color: #0b0c0c
+}
+
 .govuk-panel {
     font-family: GDS Transport, arial, sans-serif;
     -webkit-font-smoothing: antialiased;
diff --git a/dist/govuk-frontend-3.9.1.min.js b/dist/govuk-frontend-3.10.0.min.js
similarity index 54%
rename from dist/govuk-frontend-3.9.1.min.js
rename to dist/govuk-frontend-3.10.0.min.js
index fb34d417..eaee832a 100644
--- a/dist/govuk-frontend-3.9.1.min.js
+++ b/dist/govuk-frontend-3.10.0.min.js
@@ -460,14 +460,18 @@
     }
 
     function l(t) {
-        this.$module = t, this.$menuButton = t && t.querySelector(".govuk-js-header-toggle"), this.$menu = this.$menuButton && t.querySelector("#" + this.$menuButton.getAttribute("aria-controls"))
+        this.$module = t
     }
 
     function u(t) {
-        this.$module = t, this.$inputs = t.querySelectorAll('input[type="radio"]')
+        this.$module = t, this.$menuButton = t && t.querySelector(".govuk-js-header-toggle"), this.$menu = this.$menuButton && t.querySelector("#" + this.$menuButton.getAttribute("aria-controls"))
     }
 
     function d(t) {
+        this.$module = t, this.$inputs = t.querySelectorAll('input[type="radio"]')
+    }
+
+    function h(t) {
         this.$module = t, this.$tabs = t.querySelectorAll(".govuk-tabs__tab"), this.keys = {
             left: 37,
             right: 39,
@@ -616,27 +620,34 @@
             }
             return document.querySelector("label[for='" + t.getAttribute("id") + "']") || t.closest("label")
         }, l.prototype.init = function() {
+            this.$module && this.setFocus()
+        }, l.prototype.setFocus = function() {
+            var t = this.$module;
+            "true" !== t.getAttribute("data-disable-auto-focus") && "alert" === t.getAttribute("role") && (t.getAttribute("tabindex") || (t.setAttribute("tabindex", "-1"), t.addEventListener("blur", function() {
+                t.removeAttribute("tabindex")
+            })), t.focus())
+        }, u.prototype.init = function() {
             this.$module && this.$menuButton && this.$menu && (this.syncState(this.$menu.classList.contains("govuk-header__navigation--open")), this.$menuButton.addEventListener("click", this.handleMenuButtonClick.bind(this)))
-        }, l.prototype.syncState = function(t) {
+        }, u.prototype.syncState = function(t) {
             this.$menuButton.classList.toggle("govuk-header__menu-button--open", t), this.$menuButton.setAttribute("aria-expanded", t)
-        }, l.prototype.handleMenuButtonClick = function() {
+        }, u.prototype.handleMenuButtonClick = function() {
             var t = this.$menu.classList.toggle("govuk-header__navigation--open");
             this.syncState(t)
-        }, u.prototype.init = function() {
+        }, d.prototype.init = function() {
             var n = this.$module;
             r(this.$inputs, function(t) {
                 var e = t.getAttribute("data-aria-controls");
                 e && n.querySelector("#" + e) && (t.setAttribute("aria-controls", e), t.removeAttribute("data-aria-controls"))
             }), "onpageshow" in window ? window.addEventListener("pageshow", this.syncAllConditionalReveals.bind(this)) : window.addEventListener("DOMContentLoaded", this.syncAllConditionalReveals.bind(this)), this.syncAllConditionalReveals(), n.addEventListener("click", this.handleClick.bind(this))
-        }, u.prototype.syncAllConditionalReveals = function() {
+        }, d.prototype.syncAllConditionalReveals = function() {
             r(this.$inputs, this.syncConditionalRevealWithInputState.bind(this))
-        }, u.prototype.syncConditionalRevealWithInputState = function(t) {
+        }, d.prototype.syncConditionalRevealWithInputState = function(t) {
             var e = document.querySelector("#" + t.getAttribute("aria-controls"));
             if (e && e.classList.contains("govuk-radios__conditional")) {
                 var n = t.checked;
                 t.setAttribute("aria-expanded", n), e.classList.toggle("govuk-radios__conditional--hidden", !n)
             }
-        }, u.prototype.handleClick = function(t) {
+        }, d.prototype.handleClick = function(t) {
             var n = t.target;
             "radio" === n.type && r(document.querySelectorAll('input[type="radio"][aria-controls]'), function(t) {
                 var e = t.form === n.form;
@@ -658,13 +669,13 @@
                     return t
                 }
             })
-        }.call("object" == typeof window && window || "object" == typeof self && self || "object" == typeof global && global || {}), d.prototype.init = function() {
+        }.call("object" == typeof window && window || "object" == typeof self && self || "object" == typeof global && global || {}), h.prototype.init = function() {
             "function" == typeof window.matchMedia ? this.setupResponsiveChecks() : this.setup()
-        }, d.prototype.setupResponsiveChecks = function() {
+        }, h.prototype.setupResponsiveChecks = function() {
             this.mql = window.matchMedia("(min-width: 40.0625em)"), this.mql.addListener(this.checkMode.bind(this)), this.checkMode()
-        }, d.prototype.checkMode = function() {
+        }, h.prototype.checkMode = function() {
             this.mql.matches ? this.setup() : this.teardown()
-        }, d.prototype.setup = function() {
+        }, h.prototype.setup = function() {
             var t = this.$module,
                 e = this.$tabs,
                 n = t.querySelector(".govuk-tabs__list"),
@@ -678,7 +689,7 @@
                 var i = this.getTab(window.location.hash) || this.$tabs[0];
                 this.showTab(i), t.boundOnHashChange = this.onHashChange.bind(this), window.addEventListener("hashchange", t.boundOnHashChange, !0)
             }
-        }, d.prototype.teardown = function() {
+        }, h.prototype.teardown = function() {
             var t = this.$module,
                 e = this.$tabs,
                 n = t.querySelector(".govuk-tabs__list"),
@@ -688,7 +699,7 @@
             }), r(e, function(t) {
                 t.removeEventListener("click", t.boundTabClick, !0), t.removeEventListener("keydown", t.boundTabKeydown, !0), this.unsetAttributes(t)
             }.bind(this)), window.removeEventListener("hashchange", t.boundOnHashChange, !0))
-        }, d.prototype.onHashChange = function(t) {
+        }, h.prototype.onHashChange = function(t) {
             var e = window.location.hash,
                 n = this.getTab(e);
             if (n)
@@ -697,32 +708,32 @@
                     var o = this.getCurrentTab();
                     this.hideTab(o), this.showTab(n), n.focus()
                 }
-        }, d.prototype.hideTab = function(t) {
+        }, h.prototype.hideTab = function(t) {
             this.unhighlightTab(t), this.hidePanel(t)
-        }, d.prototype.showTab = function(t) {
+        }, h.prototype.showTab = function(t) {
             this.highlightTab(t), this.showPanel(t)
-        }, d.prototype.getTab = function(t) {
+        }, h.prototype.getTab = function(t) {
             return this.$module.querySelector('.govuk-tabs__tab[href="' + t + '"]')
-        }, d.prototype.setAttributes = function(t) {
+        }, h.prototype.setAttributes = function(t) {
             var e = this.getHref(t).slice(1);
             t.setAttribute("id", "tab_" + e), t.setAttribute("role", "tab"), t.setAttribute("aria-controls", e), t.setAttribute("aria-selected", "false"), t.setAttribute("tabindex", "-1");
             var n = this.getPanel(t);
             n.setAttribute("role", "tabpanel"), n.setAttribute("aria-labelledby", t.id), n.classList.add(this.jsHiddenClass)
-        }, d.prototype.unsetAttributes = function(t) {
+        }, h.prototype.unsetAttributes = function(t) {
             t.removeAttribute("id"), t.removeAttribute("role"), t.removeAttribute("aria-controls"), t.removeAttribute("aria-selected"), t.removeAttribute("tabindex");
             var e = this.getPanel(t);
             e.removeAttribute("role"), e.removeAttribute("aria-labelledby"), e.classList.remove(this.jsHiddenClass)
-        }, d.prototype.onTabClick = function(t) {
+        }, h.prototype.onTabClick = function(t) {
             if (!t.target.classList.contains("govuk-tabs__tab")) return !1;
             t.preventDefault();
             var e = t.target,
                 n = this.getCurrentTab();
             this.hideTab(n), this.showTab(e), this.createHistoryEntry(e)
-        }, d.prototype.createHistoryEntry = function(t) {
+        }, h.prototype.createHistoryEntry = function(t) {
             var e = this.getPanel(t),
                 n = e.id;
             e.id = "", this.changingHash = !0, window.location.hash = this.getHref(t).slice(1), e.id = n
-        }, d.prototype.onTabKeydown = function(t) {
+        }, h.prototype.onTabKeydown = function(t) {
             switch (t.keyCode) {
                 case this.keys.left:
                 case this.keys.up:
@@ -732,32 +743,32 @@
                 case this.keys.down:
                     this.activateNextTab(), t.preventDefault()
             }
-        }, d.prototype.activateNextTab = function() {
+        }, h.prototype.activateNextTab = function() {
             var t = this.getCurrentTab(),
                 e = t.parentNode.nextElementSibling;
             if (e) var n = e.querySelector(".govuk-tabs__tab");
             n && (this.hideTab(t), this.showTab(n), n.focus(), this.createHistoryEntry(n))
-        }, d.prototype.activatePreviousTab = function() {
+        }, h.prototype.activatePreviousTab = function() {
             var t = this.getCurrentTab(),
                 e = t.parentNode.previousElementSibling;
             if (e) var n = e.querySelector(".govuk-tabs__tab");
             n && (this.hideTab(t), this.showTab(n), n.focus(), this.createHistoryEntry(n))
-        }, d.prototype.getPanel = function(t) {
+        }, h.prototype.getPanel = function(t) {
             return this.$module.querySelector(this.getHref(t))
-        }, d.prototype.showPanel = function(t) {
+        }, h.prototype.showPanel = function(t) {
             this.getPanel(t).classList.remove(this.jsHiddenClass)
-        }, d.prototype.hidePanel = function(t) {
+        }, h.prototype.hidePanel = function(t) {
             this.getPanel(t).classList.add(this.jsHiddenClass)
-        }, d.prototype.unhighlightTab = function(t) {
+        }, h.prototype.unhighlightTab = function(t) {
             t.setAttribute("aria-selected", "false"), t.parentNode.classList.remove("govuk-tabs__list-item--selected"), t.setAttribute("tabindex", "-1")
-        }, d.prototype.highlightTab = function(t) {
+        }, h.prototype.highlightTab = function(t) {
             t.setAttribute("aria-selected", "true"), t.parentNode.classList.add("govuk-tabs__list-item--selected"), t.setAttribute("tabindex", "0")
-        }, d.prototype.getCurrentTab = function() {
+        }, h.prototype.getCurrentTab = function() {
             return this.$module.querySelector(".govuk-tabs__list-item--selected .govuk-tabs__tab")
-        }, d.prototype.getHref = function(t) {
+        }, h.prototype.getHref = function(t) {
             var e = t.getAttribute("href");
             return e.slice(e.indexOf("#"), e.length)
-        }, t.initAll = function h(t) {
+        }, t.initAll = function p(t) {
             var e = "undefined" != typeof(t = void 0 !== t ? t : {}).scope ? t.scope : document;
             r(e.querySelectorAll('[data-module="govuk-button"]'), function(t) {
                 new o(t).init()
@@ -769,10 +780,12 @@
                 new s(t).init()
             }), r(e.querySelectorAll('[data-module="govuk-checkboxes"]'), function(t) {
                 new a(t).init()
-            }), new c(e.querySelector('[data-module="govuk-error-summary"]')).init(), new l(e.querySelector('[data-module="govuk-header"]')).init(), r(e.querySelectorAll('[data-module="govuk-radios"]'), function(t) {
-                new u(t).init()
-            }), r(e.querySelectorAll('[data-module="govuk-tabs"]'), function(t) {
+            }), new c(e.querySelector('[data-module="govuk-error-summary"]')).init(), new u(e.querySelector('[data-module="govuk-header"]')).init(), r(e.querySelectorAll('[data-module="govuk-notification-banner"]'), function(t) {
+                new l(t).init()
+            }), r(e.querySelectorAll('[data-module="govuk-radios"]'), function(t) {
                 new d(t).init()
+            }), r(e.querySelectorAll('[data-module="govuk-tabs"]'), function(t) {
+                new h(t).init()
             })
-        }, t.Accordion = n, t.Button = o, t.Details = i, t.CharacterCount = s, t.Checkboxes = a, t.ErrorSummary = c, t.Header = l, t.Radios = u, t.Tabs = d
+        }, t.Accordion = n, t.Button = o, t.Details = i, t.CharacterCount = s, t.Checkboxes = a, t.ErrorSummary = c, t.Header = u, t.Radios = d, t.Tabs = h
 });
\ No newline at end of file
diff --git a/dist/govuk-frontend-ie8-3.9.1.min.css b/dist/govuk-frontend-ie8-3.10.0.min.css
similarity index 49%
rename from dist/govuk-frontend-ie8-3.9.1.min.css
rename to dist/govuk-frontend-ie8-3.10.0.min.css
index 09dcabdb..95b3e568 100644
--- a/dist/govuk-frontend-ie8-3.9.1.min.css
+++ b/dist/govuk-frontend-ie8-3.10.0.min.css
@@ -1862,21 +1862,36 @@
 }
 
 .govuk-error-summary__list a {
-    font-weight: 700
+    font-weight: 700;
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale
+}
+
+.govuk-error-summary__list a:focus {
+    background-color: #fd0;
+    box-shadow: 0 -2px #fd0, 0 4px #0b0c0c;
+    text-decoration: none
+}
+
+.govuk-error-summary__list a:link {
+    color: #d4351c
 }
 
-.govuk-error-summary__list a:active,
-.govuk-error-summary__list a:hover,
-.govuk-error-summary__list a:link,
 .govuk-error-summary__list a:visited {
+    color: #4c2c92
+}
+
+.govuk-error-summary__list a:hover {
+    color: #942514
+}
+
+.govuk-error-summary__list a:active {
     color: #d4351c
 }
 
 .govuk-error-summary__list a:focus {
-    color: #0b0c0c;
-    background-color: #fd0;
-    box-shadow: 0 -2px #fd0, 0 4px #0b0c0c;
-    text-decoration: none
+    color: #0b0c0c
 }
 
 .govuk-file-upload {
@@ -2382,6 +2397,149 @@
     margin-bottom: 0
 }
 
+.govuk-notification-banner {
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale;
+    font-weight: 400;
+    font-size: 16px;
+    font-size: 1rem;
+    line-height: 1.25;
+    font-size: 19px;
+    font-size: 1.1875rem;
+    line-height: 1.31579;
+    margin-bottom: 50px;
+    border: 5px solid #1d70b8
+}
+
+.govuk-notification-banner:focus {
+    outline: 3px solid #fd0
+}
+
+.govuk-notification-banner__header {
+    border-bottom: 1px solid transparent;
+    background-color: #1d70b8;
+    padding: 2px 20px 5px
+}
+
+.govuk-notification-banner__title {
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale;
+    font-weight: 700;
+    font-size: 16px;
+    font-size: 1rem;
+    line-height: 1.25;
+    font-size: 19px;
+    font-size: 1.1875rem;
+    line-height: 1.31579;
+    margin: 0;
+    padding: 0;
+    color: #fff
+}
+
+.govuk-notification-banner__content {
+    margin: 20px
+}
+
+.govuk-notification-banner__heading {
+    font-weight: 700;
+    font-size: 18px;
+    font-size: 1.125rem;
+    line-height: 1.11111;
+    font-size: 24px;
+    font-size: 1.5rem;
+    line-height: 1.25;
+    margin: 0 0 15px;
+    padding: 0
+}
+
+.govuk-notification-banner__heading,
+.govuk-notification-banner__link {
+    font-family: GDS Transport, arial, sans-serif;
+    -webkit-font-smoothing: antialiased;
+    -moz-osx-font-smoothing: grayscale
+}
+
+.govuk-notification-banner__link:focus {
+    background-color: #fd0;
+    box-shadow: 0 -2px #fd0, 0 4px #0b0c0c;
+    text-decoration: none
+}
+
+.govuk-notification-banner__link:link {
+    color: #1d70b8
+}
+
+.govuk-notification-banner__link:visited {
+    color: #4c2c92
+}
+
+.govuk-notification-banner__link:hover {
+    color: #003078
+}
+
+.govuk-notification-banner__link:active,
+.govuk-notification-banner__link:focus {
+    color: #0b0c0c
+}
+
+.govuk-notification-banner--success {
+    border-color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__header {
+    background-color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:link {
+    color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:visited {
+    color: #4c2c92
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:hover {
+    color: #004e2a
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:active {
+    color: #00703c
+}
+
+.govuk-notification-banner--success .govuk-notification-banner__link:focus {
+    color: #0b0c0c
+}
+
+.govuk-notification-banner--error {
+    border-color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__header {
+    background-color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:link {
+    color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:visited {
+    color: #4c2c92
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:hover {
+    color: #942514
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:active {
+    color: #d4351c
+}
+
+.govuk-notification-banner--error .govuk-notification-banner__link:focus {
+    color: #0b0c0c
+}
+
 .govuk-panel {
     font-family: GDS Transport, arial, sans-serif;
     -webkit-font-smoothing: antialiased;
```

**Comment by 36degrees** [comment]
Reset, re-ran the build script and force-pushed to include changes from #2027 and #2028 ([changes](https://github.com/alphagov/govuk-frontend/compare/1bc8039502dd7fd3eb29f33c0a2f38ccd111c582..84ea73441e15773d61501d70258a84e061f7a300))

**Comment by 36degrees** [comment]
[Force-pushed again](https://github.com/alphagov/govuk-frontend/compare/84ea73441e15773d61501d70258a84e061f7a300..a4e9ac9d70a571558e7bb25dcb675323b2a933f8) to remove erroneously-committed `.gitattributes` file 🤦🏻‍♂️

**Review by vanitabarrett — DISMISSED** [review]

**Comment by vanitabarrett** [comment]
Reset, re-ran the build script and force-pushed to include changes from https://github.com/alphagov/govuk-frontend/pull/2030

**Pull request closed without merging**
