### PR TITLE
Update Node to Active LTS version v16 (Gallium)

### LINKED ISSUE #2504: Update Node.js to active LTS version
## What

Update the project to use the latest active Long Term Support (LTS) version of Node.js for development, testing, and deployment.

## Why

This project currently uses Node.js version 14, which has been in maintenance since last October (2021-10-19) and won't receive new features.

## Who needs to work on this

Developer

## Who needs to review this

Developer, Tech lead

## Done when

- [ ] Update `.nvmrc`
- [ ] Update `package-lock.json` to use lockfile v2

### PR DESCRIPTION
**Pull request by domoscargin**
Node.js v14 has been in maintenance mode from 19 October 2021. v16 is the active LTS version.

This in turns updates NPM to v8, meaning our lockfile has changed to [`lockfileVersion` 2](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion)

This is an internal change that affects development, testing and deployment.

Closes #2504

### CODE REVIEW

**Comment by domoscargin** [comment]
> There are no plans to support M1 with the node-sass compiler. You can switch to the sass compiler instead.

https://github.com/dlmanning/gulp-sass/issues/803#issuecomment-869580225

**Comment by domoscargin** [comment]
I got this working locally by running:

`npm uninstall node-sass -g && npm cache clean -force && npm install node-sass`

**Comment by 36degrees** [comment]
I have a new M1 mac so tried switching to this branch immediately after cloning the repo, installing and using 16.14.0 _without_ having installed or run GOV.UK Frontend under v14, and was able to install and start without any issues. So wondering if this is 'only' an issue for users migrating from 14 to 16.

**Comment by 36degrees** [comment]
@vanitabarrett Yes, I think so.

**Comment by domoscargin** [comment]
In that case, I can add some troubleshooting documentation here: https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/running-locally.md

Though this does seem like a pretty temporary problem that affects a small group, so we'd probably want to review it down the line.

**Comment by EoinShaughnessy** [comment]
@domoscargin Hi!

Yeah, I think adding this content is probably a good idea - should help some users, even if only a few.

Do we have an idea of when this issue will no longer affect users?

Also, what sort of problems might they encounter? Would giving an example help users confirm the issue is to do with using Node v14 or earlier?

**Comment by domoscargin** [comment]
> Do we have an idea of when this issue will no longer affect users?
> 
> Also, what sort of problems might they encounter? Would giving an example help users confirm the issue is to do with using Node v14 or earlier?

This would stop affecting users once everybody who's installed `govuk-frontend` locally on their M1 with Node v14 has successfully moved to Node v16. This only affects devs/contributors, since most users don't need to install this repo locally. 

Once this change is in place, anybody who installs locally for the first time should have no problems. Additionally, if we migrate our build process to Dart Sass (#2239), this problem should go away for anybody who installs after that change. So it's probably a small(ish) pool of users, but with a potentially long tail depending on when they update.

The problem is specifically with the `node-sass` package. Users will get `node-sass` related errors when trying to run `npm install` or `npm start` (https://github.com/alphagov/govuk-design-system/pull/2110#issuecomment-1072333844)

**Comment by EoinShaughnessy** [comment]
@domoscargin Great explanation, thanks!

Content looks really good! Just suggesting a few tweaks*:

```
### Fixing update errors
If you've previously installed `govuk-frontend` locally using Node v14 or earlier, you may see `node-sass`-related errors when updating to Node v16.

To get rid of these errors, delete the `node_modules` folder from the `node-sass` package, then run:

nvm use
npm uninstall node-sass -g && npm cache clean -force && npm install node-sass
npm install
```

* These might be based on my misunderstanding stuff - if so, sorry!

**Review by lfdebrux — APPROVED** [review]
1️⃣ 6️⃣ 🎉

**Pull request merged**
