### PR TITLE
Allow Node.js LTS ‘Iron’ (v20) release version

### PR DESCRIPTION
**Pull request by colinrotherham**
This PR allows Node.js LTS ‘Iron’ (v20) to install, run and build **GOV.UK Frontend**

>GOV.UK Frontend requires Node.js version 12.17.0 or later to support ECMAScript modules. Where possible, we recommend you install the latest Long Term Support (LTS) version

Changes included:

1. **Updating [.browserslistrc](https://github.com/alphagov/govuk-frontend/blob/main/.browserslistrc#L2)** for Node.js 20
So Babel is aware we need to support only `node 20`

2. **Updating [.nvmrc](https://github.com/alphagov/govuk-frontend/blob/main/.nvmrc)** for Node.js 20
So tools like [nvm](https://github.com/nvm-sh/nvm#readme) and [asdf](https://github.com/asdf-vm/asdf#readme) allow the `lts/iron` LTS release

3. **Bump the [package.json `engines.node` range](https://github.com/alphagov/govuk-frontend/blob/main/package.json#L6)**
Ensures `npm install` and other scripts check the local Node.js version is allowed

3. **Bump the [package.json `engines.npm` range](https://github.com/alphagov/govuk-frontend/blob/main/package.json#L7)**
Ensure support for `npm@10` rather than `npm@9`

### CODE REVIEW

**Comment by colinrotherham** [comment]
Blocked until Node.js 20 LTS released: 24 October 2023

**Comment by colinrotherham** [comment]
Node.js 20 is now in LTS

Just waiting for https://github.com/actions/node-versions/pull/156 (to merge) and Node.js 20 to appear in the [Heroku Changelog](https://devcenter.heroku.com/changelog)

**Comment by colinrotherham** [comment]
Heroku builds are still failing, must still be rolling out:

```console
-----> Installing binaries
       engines.node (package.json):  ^20.9.0
       engines.npm (package.json):   ^10.1.0
       
       Resolving node version ^20.9.0...
       Could not find Node version corresponding to version requirement: ^20.9.0
-----> Build failed
 !     No matching version found for Node: ^20.9.0
```

We'll keep an eye on the [Heroku Changelog](https://devcenter.heroku.com/changelog)

**Comment by colinrotherham** [comment]
All sorted, ready to go:

>[**Node.js 20.9.0 and 21.1.0 now available**](https://devcenter.heroku.com/changelog-items/2704)
>Node.js versions 20.9.0 and 21.1.0 have been made available for builds on Heroku. For additional information, please see our article on [Node.js Support](https://devcenter.heroku.com/articles/nodejs-support).

**Review by romaricpascal — COMMENTED** [review]
Looking good. `nvm` was happy with `lts/iron` locally (and Github actions and Heroku) on CI, hopefully asdf won't be long. 

Do you know if people will need to update `asdf` locally for it to undersand `lts/iron`?

**Comment by colinrotherham** [comment]
@romaricpascal Nah it does an automatic update on `asdf install`

Wonder if we should use `20.x` or something similarly compatible instead of code names?

**Comment by romaricpascal** [comment]
`20.x` sounds a great way to not make us depend on the tools understanding the latest code name, so very up for that 😊

**Review by romaricpascal — APPROVED** [review]
From our discussion on Slack, it seems using `20` in `.nvmrc` causes trouble with asdf when Husky runs. That'd make `lts/iron` would be fine once `asdf` supports it, unless we figure why Husky and asdf don't play nicely.

It'll also be worth coordinating the merge with the rest of the team, so that people know to run `nvm` or `asdf` to set up the new version.

**Pull request merged**
