### PR TITLE
Add 48px favicon

### LINKED ISSUE #963: Favicon missing 48x48 size
As reported by @timja in https://github.com/alphagov/govuk_template/issues/328:

> The favicon currently has 16x16 and 32x32 resolutions.
Microsoft recommends including at least a 48x48 one as well.
Android would also use this for high definition.
https://msdn.microsoft.com/library/gg491740(v=vs.85).aspx
>
> A scan of gov.uk:
https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.gov.uk
>
> Easiest way to generate a new one given the right image:
https://realfavicongenerator.net/

This is still an issue in GOV.UK Frontend, as verified by running 'favicon checker' against the Design System:
https://realfavicongenerator.net/favicon_checker?protocol=https&site=design-system.service.gov.uk%2F#.W36AfpNKiRc

### PR DESCRIPTION
**Pull request by dashouse**
Add a single favicon with multiple sizes
Fixes #963

### CODE REVIEW

**Comment by igloosi** [comment]
can have a single file but might be side effects.
write-up https://stackoverflow.com/a/48969053

**Comment by igloosi** [comment]
updated PR:
Add a single favicon with multiple sizes
Fixes #963

**Comment by nickcolley** [comment]
@igloosi does it look different before and after?

**Comment by igloosi** [comment]
no
screen shot 2018-09-18 at 11 27 41

**Pull request merged**
