### PR TITLE
Fix footer alignment with grid classes

### PR DESCRIPTION
**Pull request by lfdebrux**
Fixes https://github.com/alphagov/govuk-frontend/issues/1539. It also partly addresses https://github.com/alphagov/govuk-frontend/issues/1726, along with https://github.com/alphagov/govuk-frontend/pull/2446

Unfortunately this PR does not fix any of the other bugs reported in https://github.com/alphagov/govuk-frontend/issues/1680

## What
Adjust the styles of the footer layout to better match up with the grid classes. The screenshot below shows the grid classes and the footer not aligning properly:

mac-chrome-left-before

**Note:** It's worth comparing and contrasting these changes with those in branch [`nickcolley-ldeb-spike-footer-grid`](https://github.com/alphagov/govuk-frontend/tree/nickcolley-ldeb-spike-footer-grid), which achieves much the same effect with fewer lines and fewer commits by using CSS grids. The CSS grid version also behaves slightly better as the viewport changes size. However, CSS grids are not supported by all browsers we want to support, so I think this PR that uses flexbox should take precedence.

Browsers to test in:

- [x] Internet Explorer 8
- [x] Internet Explorer 9
- [x] Internet Explorer 10
- [x] Internet Explorer 11
- [x] Chrome on macOS
- [x] Safari on macOS
- [x] Chrome on Windows
- [x] Firefox on macOS
- [x] Edge on Windows
- [x] Firefox on Windows
- [x] Safari on iOS
- [x] Chrome on iOS
- [x] Chrome on Android
- [x] Samsung Internet on Android

For each browser, test the two main footer examples:
 
 - https://govuk-frontend-pr-2428.herokuapp.com/examples/footer-alignment
  - https://govuk-frontend-pr-2428.herokuapp.com/components/footer
 
and zoom in to 400%.

## Screenshots
Note: this is just a sample of screenshots where the change is most visible

### IE8 GOV.UK example - Before vs After
ie8-govuk-before
ie8-govuk-after

### IE8 Two Column Left example - Before vs After
ie8-left-before
ie8-left-after

### IE8 Two Column Right example - Before vs After
ie8-right-before
ie8-right-after

### IE8 Equal Three Column example - Before vs After
ie8-three-before
ie8-three-after

### IE10 Two Column Right example - Before vs After
ie10-right-before
ie10-right-after

### CODE REVIEW

**Comment by vanitabarrett** [comment]
**Note:** this PR changes the behaviour slightly of what happens on screen sizes smaller than desktop. The previous behaviour gradually dropped the width of each column, e.g: from thirds, to halves, to full width. This PR changes that behaviour so it drops straight to full width. This means you can end up with quite a large full width footer on tablet, e.g:

## Example - before (tablet)
Screenshot 2021-12-01 at 14 40 21

## Example - after (tablet)
Screenshot 2021-12-01 at 14 40 05

We could make a change to drop down to 50% width on tablet. However, this would mean that columns that have perhaps been given more visual importance (see example below of the 'Coronavirus' section in the GOV.UK footer) would in some ways have less importance on tablet as the column below would sit alongside it.

## Desktop - Coronavirus column sits on its own row
Screenshot 2021-12-01 at 14 44 39

## Tablet - Coronavirus column sits alongside "Services and Information"
Screenshot 2021-12-01 at 14 44 53

**Comment by vanitabarrett** [comment]
Note: because https://github.com/alphagov/govuk-frontend/pull/2446 builds off the changes made in this PR, I'll add the Changelog entry in https://github.com/alphagov/govuk-frontend/pull/2446 rather than in this PR.

**Comment by lfdebrux** [comment]
@vanitabarrett 

> Note: this PR changes the behaviour slightly of what happens on screen sizes smaller than desktop. 

Do we need a designer to review this change?

**Comment by vanitabarrett** [comment]
Superseded by https://github.com/alphagov/govuk-frontend/pull/2462

**Pull request closed without merging**
