### PR TITLE
Fix govuk-equilateral-height function usage in shape-arrow helper

### PR DESCRIPTION
**Pull request by igloosi**
In #762 we changed the name of the `govuk-equilateral-height` function to `_govuk-equilateral-height` to signify that is is a private function.

Unfortunately we forgot to update the name where it was used to create the open/closed indicator for the details component.

This PR fixes this.

Before:
screen shot 2018-06-05 at 19 39 00

After: 
screen shot 2018-06-05 at 19 39 41

### CODE REVIEW

**Comment by 36degrees** [comment]
Argh, good catch - thanks for that. I think I understand why, but it's pretty annoying that Sass silently outputs the function call verbatim. I wonder if there's a way we could try and catch that if it happens.

**Comment by igloosi** [comment]
i guess only if we wrap it in a custom mixin that check if function exist using sass's built-in `function-exists`

alternatively, if we use `get-function("myfunc")` when calling a function, that will throw an error in compilation

**Comment by 36degrees** [comment]
Added a test that greps the CSS for anything matching `/govuk-[\w-]+\(.*?\)/g`, which _should_ catch most function calls that slip through the net… unless they misspell govuk…

**Comment by igloosi** [comment]
fixed the extra semicolon in the test

**Comment by 36degrees** [comment]
Added a big ole' comment around what the test is looking for

**Pull request merged**
