### PR TITLE
Ability to group radio buttons / checkboxes within sub-headings

### PR DESCRIPTION
**Pull request by colinrotherham**
This feature adds a new macro `govukFormGroup()`.

This lets us put radios/checkboxes inside a `<div class="govuk-form-group">` wrapper, nested to multiple levels with the `describedBy` variable to be persisted and appended to at each level.

It also allows the component examples to show both regular and fieldset-wrapped variations using the optional `params.fieldset`, useful to confirm bugs like https://github.com/alphagov/govuk-frontend/issues/1264

Form group

### Why else is it needed?
I've also addressed what looks like a bit of technical debt.

Duplicated inside almost all form control macros is Nunjucks code to generate a `govukLabel()` label, a `govukHint()` hint an a `govukErrorMessage()` error message.

This code here is pretty much copy and pasted 7 times:

```nunjucks
  {{ govukLabel({
    html: params.label.html,
    text: params.label.text,
    classes: params.label.classes,
    isPageHeading: params.label.isPageHeading,
    attributes: params.label.attributes,
    for: params.id
  }) | indent(2) | trim }}
{% if params.hint %}
  {% set hintId = params.id + '-hint' %}
  {% set describedBy = describedBy + ' ' + hintId if describedBy else hintId %}
  {{ govukHint({
    id: hintId,
    classes: params.hint.classes,
    attributes: params.hint.attributes,
    html: params.hint.html,
    text: params.hint.text
  }) | indent(2) | trim }}
{% endif %}
{% if params.errorMessage %}
  {% set errorId = params.id + '-error' %}
  {% set describedBy = describedBy + ' ' + errorId if describedBy else errorId %}
  {{ govukErrorMessage({
    id: errorId,
    classes: params.errorMessage.classes,
    attributes: params.errorMessage.attributes,
    html: params.errorMessage.html,
    text: params.errorMessage.text,
    visuallyHiddenText: params.errorMessage.visuallyHiddenText
  }) | indent(2) | trim }}
{% endif %}
```

It's used by textarea, select, radios, checkboxes, text input, file upload and date input.

All this boilerplate code is now handled by `govukFormGroup()`.

### CODE REVIEW

**Comment by colinrotherham** [comment]
Can we add a Heroku deployment please?

I've added a new radios/checkboxes with subheadings demo to the form examples page.

Thanks

**Comment by colinrotherham** [comment]
Pushing again, looks like I got auto-cancelled:

>This job was cancelled because the "Auto Cancellation" feature is currently enabled, and a more recent build (#7798) for pull request #1266 came in while this job was waiting to be processed.

**Comment by colinrotherham** [comment]
Thanks for the deployment @hannalaakso.

I've added the radios/checkboxes within subheadings examples here:
https://govuk-frontend-review-pr-1266.herokuapp.com/examples/form-elements

**Comment by colinrotherham** [comment]
As mentioned by @frankieroberto, I'll still need an alternative to https://github.com/alphagov/govuk-frontend/pull/1163 otherwise open conditional reveals won't close when another group's radio is clicked.

I'll take a look at this today.

**Comment by colinrotherham** [comment]
I've just added an alternative fix to https://github.com/alphagov/govuk-frontend/pull/1163.

This adds support for "Conditional reveal across sibling form groups"

Sibling-form-group-conditional-reveal

Looks like the final piece required for https://github.com/alphagov/govuk-frontend/issues/1079 (including https://github.com/alphagov/govuk-frontend/issues/1166 solved via `govukFormGroup()`)

**Comment by colinrotherham** [comment]
Initial testing of the  in IE8–11 "Conditional reveal across sibling form groups" feature works great

**Comment by colinrotherham** [comment]
Just added `'../../vendor/polyfills/Element/prototype/closest'` to **radios.js** so we've covered if anyone imports the file separately.

**Comment by aliuk2012** [comment]
Hi @colinrotherham 

Firstly, we would like to thank you for submitting this PR and for the tremendous amount of work that you have put into this PR. 
We have discussed this change as a team and would like to take this to the next GOVUK Design System Working Group on 25 April to get assurance that the pattern works from a usability point of view. 

Until a decision is made we won't be requiring anything more from you and we'll keep you updated as to the progress.

Alistair Laing
Senior Frontend Developer
GOV.UK Design System Team

**Comment by colinrotherham** [comment]
Thanks @aliuk2012.

I appreciate there are three distinct pieces of work you might want me to separate out:

1. Removing duplicate of label/hint/error with `govukFormGroup()` macro
2. Allowing `params.fieldset.describedBy` to be configured (to pass to nested fieldsets)
3. Supporting conditional reveal across sibling radio lists

We can do all or any of these in isolation.

See what you think at the working group.

**Comment by colinrotherham** [comment]
Rebased with `master`

**Comment by aliuk2012** [comment]
Hi @colinrotherham,

Just a quick update, we were reviewing what we were going to take to the working group this week and we have decided not to take this pattern to the working group. The reason is we do not feel like this would be a good pattern to introduce and there are a lot of usability issues with it.

Regarding the other changes you have proposed in this PR, we still think that they might still be worth merging but we need to discuss this as a team. 

Until a decision is made we won't be requiring anything more from you and we'll keep you updated as to the progress.

**Comment by colinrotherham** [comment]
@aliuk2012 Ah no problem.

I appreciate this pattern confuses the [One thing per page](https://www.gov.uk/service-manual/design/form-structure#start-with-one-thing-per-page) approach, and it's more applicable to our staff-facing systems so we can replicate it there instead.

### The other tidy-up changes
I've removed the new pattern commits, and pushed the other changes here: https://github.com/alphagov/govuk-frontend/pull/1281

**Comment by colinrotherham** [comment]
Rebased with `form-group-wrapper` from https://github.com/alphagov/govuk-frontend/pull/1281 so these are now separate.

**Comment by aliuk2012** [comment]
We are closing this PR as it was decided that this pattern had a lot of usability issues but we are still considering the other work that @colinrotherham has done but the additional work has now been split out into two separate PR (#1281, #1297)

**Pull request closed without merging**
