### PR TITLE
Add correct PR link to changelog

### PR DESCRIPTION
**Pull request by EoinShaughnessy**
This PR replaces a link to an issue with a link to the actual PR. Have also removed a close bracket we don't need.

### CODE REVIEW

**Comment by EoinShaughnessy** [comment]
In our changelog, the PR title for #1836 is

> Rename exported JavaScript modules to include component name

When you go to the [#1836 link](https://github.com/alphagov/govuk-frontend/issues/1836), though, the title is

> JavaScript modules are attached to the same global variable when imported individually

Can we change the PR title to match the changelog title?

**Comment by vanitabarrett** [comment]
@EoinShaughnessy Ah, interesting, that's because I mistakenly linked to the issue rather than the pull request. If we update the link (and number) to https://github.com/alphagov/govuk-frontend/pull/2426, then the titles will match. It'll need updating in the full Changelog entry on the change too - are you ok to do that?

**Comment by EoinShaughnessy** [comment]
@vanitabarrett No worries! Ta for explaining. Yeah, I can change it.

**Comment by vanitabarrett** [comment]
@EoinShaughnessy Are you ok to update line 103 to match?

**Comment by EoinShaughnessy** [comment]
@vanitabarrett Sorry, my bad - yeah, think it's updated now.

**Comment by vanitabarrett** [comment]
@EoinShaughnessy Looks good, thanks for spotting that Eoin! Would you be ok to squash the commits before I approve?

**Comment by EoinShaughnessy** [comment]
@vanitabarrett Will do! :)

**Review by vanitabarrett — APPROVED** [review]

**Pull request merged**
