### PR TITLE
Switch JSDoc parser to TypeDoc + fix issues

### PR DESCRIPTION
**Pull request by colinrotherham**
I've switched our JSDoc parser to [`typedoc`](https://github.com/TypeStrong/typedoc#readme) to fully understand our JSDoc types

This has identified properties and methods (added dynamically) accidentally missed in:

* https://github.com/alphagov/govuk-frontend/issues/3473

## Accordion

```js
accordion.$showAllButton
accordion.$showAllIcon
accordion.$showAllText
```

## Details

```js
details.$content
details.$module
details.$summary
```

## Tabs

```js
tabs.changingHash
```

# TypeDoc HTML output
The JSDoc output (via TypeDoc) can be seen on the [PR preview deployment](https://govuk-frontend-pr-3512.herokuapp.com/docs/javascript/)

TypeDoc showing Accordion class properties

### CODE REVIEW

**Comment by 36degrees** [comment]
This looks really useful, thanks @colinrotherham 👍🏻 

The PR only really seems to be describing the last commit – I don't think this needs to be split up, but it'd be good to have a bit more context on the other changes in the PR description or the commit messages?

Also wanted to flag that eslint-plugin-jsdoc v41.1.2 was released earlier today with a fix, in case it's worth updating.

**Comment by colinrotherham** [comment]
@36degrees Sorry, yep it's just to identify what's missing—I've made it a draft

For context, the first commits do address an `eslint-plugin-jsdoc` breaking change though, as the update now prefers "shorthand" types. Sadly these aren't supported by our currently-unmaintained JSDoc plugin [`jsdoc-tsimport-plugin`](https://github.com/polyforest/jsdoc-tsimport-plugin#readme)

## Before
Types without parameter names

```mjs
/** @returns {Object<string, string[]>} */
/** @returns {function(string): boolean} */
/** @returns {function(): Promise<void>} */
```

## After
Shorthand types with support for parameter names

```js
/** @returns {{ [blockName: string]: string }} */
/** @returns {(entryPath: string) => boolean} */
/** @returns {() => Promise<void>} */
```

These do improve the autocomplete tooltips in editors which is nice

**Comment by colinrotherham** [comment]
>Also wanted to flag that eslint-plugin-jsdoc v41.1.2 was released earlier today with a fix, in case it's worth updating.

I've added the `eslint-plugin-jsdoc@41.1.2` bugfix which has reported a few more missing `@returns` comments

@36degrees @romaricpascal Don't need to merge this PR, but these checks are handy to have

**Comment by colinrotherham** [comment]
@romaricpascal @36degrees I've cherry picked https://github.com/alphagov/govuk-frontend/commit/5ce73b839adda681d8dbee245960016757cadf3c from:

* https://github.com/alphagov/govuk-frontend/pull/3518

Have a quick flick through the JSDoc documentation output, see if you spot anything else:
https://govuk-frontend-pr-3512.herokuapp.com/docs/javascript/

**Pull request merged**
