### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by igloosi**
### Description
Add pull request templated

### What types of change is it?
- Internal

### Reference ticket / issue
Issue: #579 

### Checklist
- [x] CHANGELOG updated

### CODE REVIEW

**Comment by hannalaakso** [comment]
It'd be good to add something about what testing has been done on the work. I stole the below from https://github.com/alphagov/govuk-frontend/pull/569

The below might be too much for every single small change but maybe we could establish what our minimum testing criteria is? 

## Testing

<details>
<summary>Inverse colours ✅</summary>
screen shot 2018-03-05 at 17 12 49
</details>

<details>
<summary>Cross browser testing ✅</summary>

### Known issues:
- Note that some of the older browser have centered crest logo, this is now left aligned to fix an issue and section break. Has been tested with my eyes but not re-screenshotted.

<details>
<summary>IE8</summary>

ie8 top

ie8 bottom

Fixed (html5 shiv):

fixed ie8 top
fixed ie8 bottom

</details>

<details>
<summary>IE9</summary>

ie9 top

ie9 bottom
</details>

<details>
<summary>IE11 (IE10 looks similar)</summary>

ie11

</details>

<details>
<summary>Edge</summary>
edge

</details>

<details>
<summary>Windows, Chrome</summary>
windows chrome

</details>

<details>
<summary>Windows, Firefox</summary>
windows firefox

</details>

<details>
<summary>Mac, Safari</summary>
mac safari
</details>

<details>
<summary>Mac, Chrome</summary>
mac chrome
</details>

<details>
<summary>Mac, Firefox</summary>
mac firefox
</details>

<details>
<summary>iPhone 6s</summary>
iphone 6s

After fix:
iphone 6s

</details>

<details>
<summary>iPhone X</summary>
iphonex top
iphonex bottom
</details>
<details>
<summary>Android, Chrome</summary>
android chrome top
android chrome bottom
</details>

<details>
<summary>Android, Firefox</summary>
android firefox top
android firefox bottom
</details>

<details>
<summary>Windows phone</summary>
windows phone

After fix:
windows phone after fix


</details>

---


| Operating system | Browser                             | Tested                                                                                                         |
|------------------|-------------------------------------|----------------------------------------------------------------------------------------------------------------|
| Windows          | Internet Explorer 8-10              | ✅ Windows 7, IE 8 - 10                                                                                           |
|                  | Internet Explorer 11                | ✅ Windows 7, IE 11                                                                                               |
|                  | Edge (latest versions)              | ✅ Windows 10, Edge 16                                                                                            |
|                  | Google Chrome (latest versions)     | ✅ Windows 10, Chrome 64                                                                                          |
|                  | Mozilla Firefox (latest versions)   | ✅ Windows 10, Firefox 58                                                                                         |
| macOS            | Safari 9+                           | ✅ macOS High Sierra, Safari 11- macOS El Capitan, Safari 9.1                                                     |
|                  | Google Chrome (latest versions)     | ✅ macOS High Sierra, Chrome 61                                                                                   |
|                  | Mozilla Firefox (latest versions)   | ✅ macOS High Sierra, Firefox 57                                                                                  |
| iOS              | Safari 9.3+                         | ✅ iPhone 6S, iOS 9, Safari - iPhone 6, iOS 8, Safari - iPhone 7, iOS 10, Safari                                  |
|                  | Google Chrome (latest versions)     | ✅(see Safari iPhone 6s) iPhone 6s, iOS 8, Chrome                                                                                       |
| Android          | Mozilla Firefox (latest versions)   | ✅ Samsung Galaxy S8, Firefox                                                                                     |
|                  | Google Chrome (latest versions)     | ✅ Samsung Galaxy S8, Chrome |
| Windows Phone    | Internet Explorer (latest versions) | ✅ Windows Phone, Lumia 930 8.1                                                                                   |


</details>


<details>
<summary>Assistive technology testing ✅(see notes below)</summary>

| Software                 | Version        | Type               | Browser                                                           | Tested |
|--------------------------|----------------|--------------------|-------------------------------------------------------------------|--------|
| JAWS                     | 15 or later    | screen reader      | Internet Explorer 11                                              | ✅Jaws 18 works fine, Jaws 17, Jaws 16, Jaws 15 |
| ZoomText                 | 10.11 or later | screen magnifier   | Internet Explorer 11                                              | ✅Right most column could be missed, however underlines in headings could help lead people but that's not guaranteed.   |
| Dragon NaturallySpeaking | 11 or later    | speech recognition | Internet Explorer 11                                              | ✅Clicking on links and images works   |
| NVDA                     | 2016 or later  | screen reader      | Mozilla Firefox (latest versions)                                 | ✅headings can be read out, lists are announced as expected, images have accessible names, passes criteria   |
| VoiceOver                | n/a            | screen reader      | Safari 10 (or higher) on Mac OS X 10.10, and iOS 10.3 (or higher) | ✅headings and lists can be tabbed through and make sense.    |

</details>

**Comment by nickcolley** [comment]
I'm worried that external contributors will be put off if they need to fill in lots of details at this stage. If we want additional information should we mark it as optional?

**Comment by hannalaakso** [comment]
That's true. Maybe we could do it the other way around and ask them to confirm what testing they've done? I would maybe be a bit worried if a UI change had only been tested in Chrome so it'd be good to know that when the PR comes in?

**Comment by igloosi** [comment]
closing this. we need to decide what goes into the template

**Pull request closed without merging**
