### PR TITLE
Add tests for skip link

### PR DESCRIPTION
**Pull request by 1pretz1**
Paired with Nick Colley to write tests for 'skip link' component, https://trello.com/c/7vIsgfGw/653-automated-tests-for-skip-link-component

### CODE REVIEW

**Comment by nickcolley** [comment]
Hey :)

The tests have failed because external contributors cannot run Tenon as it uses secrets, [I'll get this to run for you](https://docs.publishing.service.gov.uk/manual/howto-merge-a-pull-request-from-an-external-contributor.html).

**Comment by 1pretz1** [comment]
screen shot 2018-02-05 at 16 15 11

Screenshot of focused 'split-link' component

**Comment by alex-ju** [comment]
👍 well done! you'll have to rebase unfortunately 😄

**Comment by nickcolley** [comment]
Thanks Peter! 💯

**Pull request merged**
