### PR TITLE
Trigger setAttributes on all radio inputs

### PR DESCRIPTION
**Pull request by frankieroberto**
This enables the conditional reveals to work where two different macros are used with the same name attribute (eg to enable grouping of radio inputs).

One possible fix for #1079.

### CODE REVIEW

**Comment by frankieroberto** [comment]
@igloosi fixed, thanks.

**Comment by nickcolley** [comment]
Hey Frankie,

Thanks for the suggestion.

I think we need to fix this in a way that doesn't look for inputs on the document, as that's created bugs in the past.

We're going to see what @colinrotherham has found out from his research and consider a fix based on that.

Are you OK for me to close this based on that?

**Comment by frankieroberto** [comment]
@nickcolley can you explain what the issues are? Maybe there's a way to avoid them?

I did consider whether the event could be triggered on only the radio inputs which shared the same `name` attribute, but that was a bigger refactor, and triggering it on all radio buttons didn't seem to have any side-effects.

**Comment by nickcolley** [comment]
You can see this bug: https://github.com/alphagov/govuk-frontend/pull/1156

Let me know if you have any ideas. 👍

**Comment by nickcolley** [comment]
I've spoken to @frankieroberto and since this is not blocking him immediately anymore we're going to close this and action the corresponding issue when we have time https://github.com/alphagov/govuk-frontend/issues/1079.

Thanks @frankieroberto for helping us figure this out.

**Pull request closed without merging**
