### PR TITLE
Fix inline radios

### PR DESCRIPTION
**Pull request by 36degrees**
Turns out we do actually have a style for inline radios, it's just not documented or easy to apply. (h/t to @dashouse for spotting this…)

screen shot 2018-03-15 at 09 31 17

Introduce a modifier at the block level which makes all radios within that block inline. You can’t add classes to the individual radio items using the macro, and it doesn’t really make sense to require the modifier to be applied to every individual element.

Add an example of inline radios so that they are represented in the review app.

Update the readme.

### CODE REVIEW

**Comment by igloosi** [comment]
CH CH CH CHANGELOG :)

**Comment by 36degrees** [comment]
Updated.

🎵*Just gonna have to be a different man*
*Time may change me,*
*But I can't trace time* 🎵

**Comment by 36degrees** [comment]
Sorry @igloosi – one more commit to check.

**Comment by igloosi** [comment]
it's good, though i feel like using inline radios is when you have shortly worded selection which should fit side-by-side on mobile.
but you never know, so better be safe ✅

**Comment by 36degrees** [comment]
Don't disagree, but from talking to @dashouse I think matching the existing behaviour in Elements is the right thing to do for now.

**Pull request merged**
