### PR TITLE
Fix spelling of the colour fuchsia.

### PR DESCRIPTION
**Pull request by 36degrees**
As raised in https://github.com/alphagov/govuk_elements/issues/561

### CODE REVIEW

**Comment by nickcolley** [comment]
Could we reference the original issue, and if possible credit the original contributor?

**Comment by 36degrees** [comment]
Good call – done.

**Comment by edwardhorsford** [comment]
Any thoughts on if this should / could go out with a depreciation warning and not as a breaking change? Unsure if that's possible or not.

**Comment by 36degrees** [comment]
It's something we'd like to explore in the future, but we're not set up for that yet.

As only a limited number of beta partners are using it, and I would be very surprised if any of them are using this colour in their applications, I'm happy we can do this as a breaking change.

**Pull request merged**
