### PR TITLE
Remove gulp-stylelint in preparation for Stylelint 14

### PR DESCRIPTION
**Pull request by kevindew**
Hello again :wave:, 

I'm currently investigating the upgrade of [stylelint-config-gds to Stylelint 14](https://github.com/alphagov/stylelint-config-gds/pull/22) which has involved testing rules against govuk-frontend. One of the challenges has been the usage of gulp-stylelint which seems to no longer be actively maintained and doesn't support Stylelint versions greater than 13.

It doesn't appear that this module adds much value to this project, switching to use stylelint directly via NPM is pretty lightweight and makes the linting approach consistent with JS linting.

I took the liberty of specifying consistent lint tasks in the package.json file, I'm not too precious about them though so please let me know if you have alternative ideas you'd like trying out.

### CODE REVIEW

**Comment by vanitabarrett** [comment]
Hi @kevindew , thanks for raising this PR - I think we're all quite happy to get a chance to tidy up our gulp tasks and dependencies a bit! I'm wondering if there's a halfway stage where we can replace `gulp-stylelint` with `stylelint`, but continue to keep it as a gulp task to allow us to have linting while we run the review app and testing changes. I think this change means we lose that ability at the moment.

I think it should be possible to write a gulp task similar to what we've got now in `stylelint.js` using the stylelint Node API docs. Totally happy for us to take a look at that though, as I'm aware it's probably more work than you intended when raising this PR!

**Comment by kevindew** [comment]
Thanks for taking a look Vanita 👍 

Maybe we've got wires crossed but I'm not sure why you'd need a halfway stage? this doesn't remove any linting, it just moves how it occurs to be part of the [`npm test` task](https://github.com/alphagov/govuk-frontend/pull/2512/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R19). So there won't be a period without (S)CSS linting nor will there need to be new stuff added when you migrate to Sylelint 14.

I may have misunderstood your concern though, so do let me know.

**Comment by vanitabarrett** [comment]
@kevindew I think this PR loses the ability to lint while we're running the review app, for example: if we run `npm start` (behind the scenes, this does `gulp dev`) it will lint and spin up a review app. If we then make changes to our CSS, normally that would automatically be flagged by the linter too. I'm pretty sure from my testing that no longer seemed to be the case, I think because we've removed the `scss:lint` task from the gulp `styles` task series.

Our gulp tasks are really confusing at the moment, so it's not easy to follow the chain of tasks (we've got some work to revisit that at some point), but you should be able to notice a difference when you run `npm start` on `main` compared to this branch.

**Comment by vanitabarrett** [comment]
On main

```
govuk-frontend vanitabarrett$ npm start

> govuk-frontend-repository@ prestart /Users/vanitabarrett/designsystem/govuk-frontend
> node bin/check-nvmrc.js


> govuk-frontend-repository@ start /Users/vanitabarrett/designsystem/govuk-frontend
> gulp dev

[16:04:33] Using gulpfile ~/designsystem/govuk-frontend/gulpfile.js
[16:04:33] Starting 'dev'...
[16:04:33] Starting 'clean'...
[16:04:33] Finished 'clean' after 52 ms
[16:04:33] Starting 'copy-assets'...
[16:04:33] Starting 'styles'...
[16:04:33] Starting 'scss:lint'...
[16:04:40] Finished 'scss:lint' after 6.53 s
[16:04:40] Starting 'scss:compile'...
[16:04:40] Starting 'compileStyles'...
[16:04:40] Starting 'compileOldIE'...
[16:04:40] Starting 'compileLegacy'...
[16:04:40] Starting 'compileLegacyIE'...
[16:04:40] Starting 'compileFullPageStyles'...
[16:04:40] Finished 'scss:compile' after 1.16 ms
[16:04:40] Finished 'styles' after 6.54 s
[16:04:40] Starting 'scripts'...
[16:04:40] Finished 'compileStyles' after 5.24 ms
[16:04:40] Finished 'compileOldIE' after 514 ms
[16:04:40] Finished 'compileLegacy' after 515 ms
[16:04:40] Finished 'compileLegacyIE' after 517 ms
[16:04:40] Finished 'compileFullPageStyles' after 519 ms
[16:04:40] Starting 'js:compile'...
[16:04:41] Finished 'js:compile' after 69 ms
[16:04:41] Finished 'scripts' after 588 ms
[16:04:41] Finished 'copy-assets' after 7.12 s
[16:04:41] Starting 'sassdoc'...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[16:04:43] Finished 'sassdoc' after 2.93 s
[16:04:43] Starting 'serve'...
[16:04:43] Starting 'watch'...
[16:04:43] Starting 'nodemon'...
[16:04:44] Finished 'watch' after 18 ms
Server started at http://localhost:3000
```

This branch (note the missing scss:lint task)

```
govuk-frontend vanitabarrett$ npm start

> govuk-frontend-repository@ prestart /Users/vanitabarrett/designsystem/govuk-frontend
> node bin/check-nvmrc.js


> govuk-frontend-repository@ start /Users/vanitabarrett/designsystem/govuk-frontend
> gulp dev

[16:02:51] Using gulpfile ~/designsystem/govuk-frontend/gulpfile.js
[16:02:51] Starting 'dev'...
[16:02:51] Starting 'clean'...
[16:02:51] Finished 'clean' after 56 ms
[16:02:51] Starting 'copy-assets'...
[16:02:51] Starting 'styles'...
[16:02:51] Starting 'scss:compile'...
[16:02:51] Starting 'compileStyles'...
[16:02:51] Starting 'compileOldIE'...
[16:02:51] Starting 'compileLegacy'...
[16:02:51] Starting 'compileLegacyIE'...
[16:02:51] Starting 'compileFullPageStyles'...
[16:02:51] Finished 'scss:compile' after 1.25 ms
[16:02:51] Finished 'styles' after 2.74 ms
[16:02:51] Starting 'scripts'...
[16:02:51] Finished 'compileStyles' after 15 ms
[16:02:52] Finished 'compileOldIE' after 1.24 s
[16:02:52] Finished 'compileLegacy' after 1.24 s
[16:02:52] Finished 'compileLegacyIE' after 1.24 s
[16:02:52] Finished 'compileFullPageStyles' after 1.24 s
[16:02:52] Starting 'js:compile'...
[16:02:52] Finished 'js:compile' after 77 ms
[16:02:52] Finished 'scripts' after 1.32 s
[16:02:52] Finished 'copy-assets' after 1.32 s
[16:02:52] Starting 'sassdoc'...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[16:02:56] Finished 'sassdoc' after 3.45 s
[16:02:56] Starting 'serve'...
[16:02:56] Starting 'watch'...
[16:02:56] Starting 'nodemon'...
[16:02:56] Finished 'watch' after 17 ms
Server started at http://localhost:3000
```

**Comment by vanitabarrett** [comment]
And the normal kind of output you'd get when running `npm start` when there's an issue with the Sass:

```
[16:08:18] Starting 'scss:lint'...
[16:08:23] 

src/govuk/components/accordion/_index.scss
 19:5  ✖  Expected "margin-top" to come before "padding-bottom"   order/properties-order



[16:08:23] 'scss:lint' errored after 5.04 s
[16:08:23] Error in plugin "gulp-stylelint"
Message:
    Failed with 1 error
Details:
    domainEmitter: [object Object]
    domainThrown: false

[16:08:23] 'styles' errored after 5.05 s
[16:08:23] 'copy-assets' errored after 5.05 s
[16:08:23] 'dev' errored after 5.1 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! govuk-frontend-repository@ start: `gulp dev`
npm ERR! Exit status 1
npm ERR! 
```

**Comment by kevindew** [comment]
Excellent, thank you. Sorry I was not aware of that use case - the examples were really helpful.

Hmm so the interesting thing about that is that you're currently in the situation where you have SCSS linting when you do `npm start` but no JS linting until you do `npm test`. This inconsistency strikes me as something to resolve, but you might know better than me if that was a conscious choice.

I assume that you want the linting to occur each time the files are rebuilt rather than just at the start. My first thought was `npm run lint && gulp dev` but I don't think that's enough.

**Comment by vanitabarrett** [comment]
Yep, 100% - I'm not sure if it was intentional but it's probably something for us to fix! Like I said, we have got some tech debt cards written up to revisit 1) our use of Gulp generally, and 2) the fact that our tasks are pretty confusing and do multiple things. We *think* we might look at that alongside some other work in the next couple of months, but I guess for now we're keen not to lose the linting behaviour we currently have. It wouldn't be a huge issue, but more of an annoyance to push work up to Github only to then find out it fails linting.

Yep - I tried a couple of combinations in the npm task but they didn't seem to work either, which is why I'm wondering if keeping the `scss:lint` gulp task but switching it to using `stylelint` might be an option?

**Comment by kevindew** [comment]
Great thanks, I'll have a little think and get back to you. It could be that I've just underestimated the value gulp-stylelint provides you or perhaps it's easy enough to call npm tasks with gulp 🤔

**Comment by vanitabarrett** [comment]
Thanks @kevindew , appreciate it. I'll also attach this card to the other Github issues we've got to look at Gulp. Not sure how urgent the upgrade to Stylelint is, but if we happen to pick up revisiting our Gulp tasks before that happens then this problem may also just go away if we decide to move away from Gulp.

**Comment by kevindew** [comment]
That's great.

I've had a quick go at re-implementing the linting into the gulp watch flow and spawning a process to run the npm tasks to lint for both JS and SCSS. Do you want to try it out and see if I've understood your expectations right? I still need to annotate the commit message and perhaps add some comments to the code.

**Comment by vanitabarrett** [comment]
@kevindew - I've had a test, the JS linting task seems to work perfectly, but the `scss:lint` task isn't outputting anything 🤔 I've been digging into it a bit but haven't managed to figure out why yet.

**Comment by kevindew** [comment]
> @kevindew - I've had a test, the JS linting task seems to work perfectly, but the `scss:lint` task isn't outputting anything 🤔 I've been digging into it a bit but haven't managed to figure out why yet.

Oops there was a bug with the globbing for stylelint as it relied on the OS. I've fixed that now by wrapping the paths in quotes which resolves the problem.

I've also added documentation to the commit now.

**Comment by vanitabarrett** [comment]
Thanks @kevindew , just tested and the behaviour is as expected so looks good to me! I'm going to ask someone else from the Design System team to take a look too, as this is technically an external PR which needs 2 reviews.

**Review by domoscargin — APPROVED** [review]
Thanks, @kevindew - this is all working as expected for me. Always nice to drop a dependency!

**Review by vanitabarrett — APPROVED** [review]

**Pull request merged**
