### PR TITLE
Remove ↑ up and ↓ down arrow key bindings from tabs

### PR DESCRIPTION
**Pull request by querkmachine**
Currently the Tabs component binds the up and down arrow keys to the same functionality as the left and right arrow keys, using them to navigate between the previous and next tabs within a tablist. 

Last week, [we received a comment stating that these bindings were causing problems in NVDA](https://github.com/alphagov/govuk-design-system-backlog/issues/100#issuecomment-2217329666), as the user became 'trapped' within the tablist and could not arrow out of it—up and down arrows being a frequent control mechanism for moving between adjacent elements.

This morning, [we received another comment stating the opposite](https://github.com/alphagov/govuk-design-system-backlog/issues/100#issuecomment-2238652113), and that the up/down bindings weren't necessarily problematic and that a user could 'break out' by switching to NVDA's document mode.

The [example pattern in the WAI-ARIA Authoring Practices](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/#keyboardinteraction) explicitly states that only the arrow keys matching the physical direction of the tablist should be bound to tab changes (left/right for a horizontal list, up/down for a vertical list). 

On this basis, I think we should remove the existing key bindings for the up/down arrows.

## Changes

- Removes up and down arrow `keydown` bindings in the Tabs component.

## Todo 

There's an open-ended question about whether this constitutes a breaking change or not. Is it removing functionality or altering it? Or is it just fixing something that's unexpected? I've avoided adding a changelog just yet so we can ponder that. 

## Thoughts

I initially experimented with rebinding the up and down arrows to move focus between the tablist and the tab panel, as suggested [in this issue](https://github.com/alphagov/govuk-frontend/issues/860), however this still felt like it had a high risk of being incongruous with how an assistive technology user expects their tools to behave and it isn't a behaviour suggested by WAI-ARIA, so I backtracked on doing that in this PR. [You can see that work in a separate branch.](https://github.com/alphagov/govuk-frontend/compare/tabs-remove-up-down-keybinding...tabs-down-arrow-focuses-panel?expand=1)

This does not resolve the other recent issue with the Tabs component in NVDA/Firefox. https://github.com/alphagov/govuk-frontend/issues/5154

### CODE REVIEW

**Comment by selfthinker** [comment]
I don't have any concerns from an accessibility perspective.

But I wonder if it could be a problem if users got used to using the up/down arrow keys and would now be missing the functionality. It might be difficult to find out if that is the case or not. And even if that turns out to be true, it might not be a reason to not remove them. There are certainly lots of tab components out there in other design systems and other websites that only support left/right, so users should generally be used to the that.
What do others think?

**Comment by romaricpascal** [comment]
> But I wonder if it could be a problem if users got used to using the up/down arrow keys and would now be missing the functionality. It might be difficult to find out if that is the case or not. And even if that turns out to be true, it might not be a reason to not remove them. There are certainly lots of tab components out there in other design systems and other websites that only support left/right, so users should generally be used to the that.
What do others think?

Looking at the change, it's a fairly easy one to reverse should we discover we're in the wrong and release a patch.

The change looks good to merge. Interesting that there's no tests for these keys (looks like we're only testing for 'ArrowRight' in [tabs.puppeteer.test.js](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js). I'll create an issue to test add tests for ArrowLeft at least (if there's none already) so we close that gap in a separate PR.

That leaves the question of statuating on whether it's a breaking change or not before we merge, which we can discuss on Slack or at dev catch-up.

**Comment by romaricpascal** [comment]
Digging a bit actually, looks like Bootstrap is also having some proposed changes by a user on their Tabs to remove the support for up/down arrows. This comment makes a good point about [the need for both up/down and left/right when the tab list can be scrolled](https://github.com/twbs/bootstrap/issues/39969#issuecomment-2241035192). However, our tabs do not scroll, but reflow when too many tabs are present, so I think it's safe for us to remove.

**Comment by selfthinker** [comment]
> Bootstrap is also having some proposed changes by a user on their Tabs to remove the support for up/down arrows.

They also make a good point that the standard behaviour of up/down arrow keys to scroll the page breaks for non-SR keyboard users. Another reason to remove it.

**Review by owenatgov — COMMENTED** [review]
I agree with Romaric and Anika's takes in the convo of this PR. Reckon this is hot to go.

As for the type of change, I'd like to make a case that it's _not_ a breaking change on the basis that we're not making any changes to the 'API' of govuk-frontend, even if it impacts functionality. The only way I can see in which this could be breaking for someone is if they have an automated test that checks for the up down arrow interaction. That's possible but IMO not likely and not critical. Generally speaking, 'functionality' is on the other side of the line we've drawn on what is and isn't breaking and I don't think this is a reason to change our minds on that.

Not expecting us to come to a conclusion on this now. Just airing my thoughts on this.

**Comment by querkmachine** [comment]
I've added it as a fix entry in the changelog.

**Review by romaricpascal — APPROVED** [review]
Looks all good with the fix entry, thanks ⛵

**Pull request merged**
