### PR TITLE
Update heroku stack from v.16 to v.18

### PR DESCRIPTION
**Pull request by aliuk2012**
Updates Heroku from [heroku-16](https://devcenter.heroku.com/articles/heroku-16-stack) to [heroku-18](https://devcenter.heroku.com/articles/heroku-18-stack).

I've tested the review app and everything still works as expected. 

Login to team heroku account and visit https://dashboard.heroku.com/apps/govuk-frontend-review-pr-1508/settings to confirm the stack that's being used

### CODE REVIEW

**Comment by 36degrees** [comment]
Any idea why the automated deployment didn't kick in for this?

**Comment by aliuk2012** [comment]
Good question, it did spin it up. I've just deleted the review app and rebuilt it

**Comment by aliuk2012** [comment]
Its working now ^

Plus it worked first time in the other PR https://github.com/alphagov/govuk-prototype-kit/pull/775

**Comment by aliuk2012** [comment]
I'm not merging this as this PR was merely to test the heroku stack and ensure its work. I have manually upgraded the stack from the heroku dashboard

image

**Pull request closed without merging**
