### PR TITLE
Add  brand class name for Department for Business Innovation and Skills 

### PR DESCRIPTION
**Pull request by davidgisbey**
## Description

Department for Business Innovation and Skills has been broken into several departments. We've been asked to update the branding class to department-for-energy-security-and-net-zero.

## Trello card

https://trello.com/c/XYjCuXRz/1325-update-old-bis-colour-name-in-whitehall

### CODE REVIEW

**Review by colinrotherham — COMMENTED** [review]
Thanks @davidgisbey

Would you mind please duplicating the entry ([like with others](https://github.com/alphagov/govuk-frontend/commit/995412ce925eab80dfd35f67cfbf810c031633d4) + [changelog](https://github.com/alphagov/govuk-frontend/commit/b6c9794beda481392dd35460f4430109da634443#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR98)) to avoid breaking Sass that still refers to `department-for-business-innovation-skills`?

**Comment by davidgisbey** [comment]
Thanks @colinrotherham. Quick question. We've got a draft PR open to update Whitehall to use the new class name. https://github.com/alphagov/whitehall/compare/main...update-bis-brand-colour-name

I've marked it as do not merge. 

@beccapearce has pointed me to these PRs https://github.com/alphagov/govuk-frontend/pull/3407 https://github.com/alphagov/govuk-frontend/pull/3523

Is this something you'd want to batch up with those changes?

**Comment by querkmachine** [comment]
It's definitely my preference that all of the departmental name and colour changes be bundled together under #3407, as that includes some wider reaching changes to how we define and provide organisation colours. 

I've been working with Design102 and GCS to try and have the definitive departmental colours authoritatively defined. It's been slow progress, as there seems to be little organisational knowledge over what they should be for the new departments.

This PR contributes to that confusion, which has DESNZ inheriting BEIS blue (`#003479`) when the the sources I've been in contact with say that DESNZ should be green (`#00A33B`)! Not ascribing blame to you or anyone else, but it's evidence of how this information seems poorly defined and distributed, and why updates to organisation colours have historically been very slow and piecemeal. Hopefully will be changing that soon. 🤞

**Comment by querkmachine** [comment]
As per my last comment, we would prefer to batch these changes into our larger organisation colour update in #3407. As such, I'm going to close this PR for now.

**Pull request closed without merging**
