### PR TITLE
Reduce dependencies for review app

### PR DESCRIPTION
**Pull request by colinrotherham**
This PR removes the following `dependencies` from the Review app Heroku install:

```
cheerio
jest-axe
```

By creating a new [**lib/nunjucks-helpers.js**](https://github.com/alphagov/govuk-frontend/blob/app-test-packages/lib/nunjucks-helpers.js) from [**lib/jest-helpers.js**](https://github.com/alphagov/govuk-frontend/blob/app-test-packages/lib/jest-helpers.js)

Our Sass tests no longer initialise a Nunjucks environment too

Split from PR https://github.com/alphagov/govuk-frontend/pull/3411

### CODE REVIEW

**Comment by stevenjmesser** [comment]
Explanation needs adding of what this changes / makes better / makes worse. Or why it has been added.

**Comment by colinrotherham** [comment]
Hi @stevenjmesser

We reduced our Review app install size down from ~223 MB to 70MB in this PR:

* https://github.com/alphagov/govuk-frontend/pull/3004

But to get a fix out we reversed some of that here:

* https://github.com/alphagov/govuk-frontend/pull/3411

There's no rush on this PR, was only to address feedback to [split it out out](https://github.com/alphagov/govuk-frontend/pull/3411#issuecomment-1482861227) and prevent impact on EtP (see [patch](https://github.com/alphagov/govuk-frontend/pull/3413))

**Review by romaricpascal — APPROVED** [review]
Neat split of the helpers alongside the move of the dependencies to `devDependencies`! 🙌🏻  I'd welcome the return of a helper for the `cheerio.load(render(...))` calls, but that's something that can happen once we've merged other PRs that depend on this one to avoid some untimely rebasing 😄 

Let's also make sure we update the Exit this page branch to use the new location of the helpers 😊

**Comment by colinrotherham** [comment]
Thanks @romaricpascal. Exit this page helper locations PR:

* https://github.com/alphagov/govuk-frontend/pull/3413

**Pull request merged**
